version: '3.1'

services:
  sports-shop-mysql:
    image: mysql
    restart: always
    container_name: "sports-shop-mysql-container"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3307"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - sports-shop-mysql-data:/var/lib/mysql

  sports-shop-redis:
    image: "redis:latest"
    container_name: "sports-shop-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - sports-shop-redis-data:/data

volumes:
  sports-shop-redis-data:
  sports-shop-mysql-data: